// This file is auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // Tables will be generated here by Supabase CLI
    }
    Views: {
      // Views will be generated here by Supabase CLI
    }
    Functions: {
      // Functions will be generated here by Supabase CLI
    }
    Enums: {
      // Enums will be generated here by Supabase CLI
    }
  }
}
